-- Xóa bằng truncate gặp lỗi khóa ngoại, cách fix:
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `laptop_category`;
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `laptop_gpu`;
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `laptop_images`;
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `laptop`;
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `laptop_color`;
SET FOREIGN_KEY_CHECKS = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM `user`;
SET SQL_SAFE_UPDATES = 1;

-- Xóa bằng delete gặp lỗi Safe Update Mode, cách fix:  
SET SQL_SAFE_UPDATES = 0;
DELETE FROM `laptop`;
SET SQL_SAFE_UPDATES = 1;
SELECT * FROM laptop_shop.color;
SHOW TABLE STATUS LIKE 'brand';
ALTER TABLE color AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM `category`;
SET SQL_SAFE_UPDATES = 1;
SELECT * FROM laptop_shop.color;
SHOW TABLE STATUS LIKE 'category';
ALTER TABLE color AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM `color`;
SET SQL_SAFE_UPDATES = 1;
SELECT * FROM laptop_shop.color;
SHOW TABLE STATUS LIKE 'color';
ALTER TABLE color AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM `cpu`;
SET SQL_SAFE_UPDATES = 1;
SELECT * FROM laptop_shop.color;
SHOW TABLE STATUS LIKE 'cpu';
ALTER TABLE color AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM `cpu_tech`;
SET SQL_SAFE_UPDATES = 1;
SELECT * FROM laptop_shop.color;
SHOW TABLE STATUS LIKE 'cpu_tech';
ALTER TABLE color AUTO_INCREMENT = 1;

-- Xóa các bảng khác
SET SQL_SAFE_UPDATES = 0;
DELETE FROM `gpu`;
SET SQL_SAFE_UPDATES = 1;
SELECT * FROM laptop_shop.color;
SHOW TABLE STATUS LIKE 'gpu';
ALTER TABLE color AUTO_INCREMENT = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM `os_version`;
SET SQL_SAFE_UPDATES = 1;
SELECT * FROM laptop_shop.color;
SHOW TABLE STATUS LIKE 'os_version';
ALTER TABLE color AUTO_INCREMENT = 1;

