export const FETCH_IMAGE_CAROUSEL_REQUEST = "FETCH_IMAGE_CAROUSEL_REQUEST";
export const FETCH_IMAGE_CAROUSEL_SUCCESS = "FETCH_IMAGE_CAROUSEL_SUCCESS";
export const FETCH_IMAGE_CAROUSEL_FAIL = "FETCH_IMAGE_CAROUSEL_FAIL";
