
export const CREATE_LAPTOP_REQUEST = 'CREATE_LAPTOP_REQUEST';
export const CREATE_LAPTOP_SUCCESS = 'CREATE_LAPTOP_SUCCESS';
export const CREATE_LAPTOP_FAILURE = 'CREATE_LAPTOP_FAILURE';

export const UPLOAD_FILES_REQUEST = "UPLOAD_FILES_REQUEST";
export const UPLOAD_FILES_SUCCESS = "UPLOAD_FILES_SUCCESS";
export const UPLOAD_FILES_FAILURE = "UPLOAD_FILES_FAILURE";

export const UPDATE_LAPTOP_REQUEST = "UPDATE_LAPTOP_REQUEST";
export const UPDATE_LAPTOP_SUCCESS = "UPDATE_LAPTOP_SUCCESS";
export const UPDATE_LAPTOP_FAILURE = "UPDATE_LAPTOP_FAILURE";

export const DELETE_LAPTOP_REQUEST = "DELETE_LAPTOP_REQUEST";
export const DELETE_LAPTOP_SUCCESS = "DELETE_LAPTOP_SUCCESS";
export const DELETE_LAPTOP_FAILURE = "DELETE_LAPTOP_FAILURE";
/*chỉ cho customer*/
export const GET_LAPTOPS_REQUEST = 'GET_LAPTOP_REQUEST';
export const GET_LAPTOPS_SUCCESS = 'GET_LAPTOP_SUCCESS';
export const GET_LAPTOPS_FAILURE = 'GET_LAPTOP_FAILURE';

export const FIND_LAPTOP_BY_ID_REQUEST = 'FIND_LAPTOP_BY_ID_REQUEST';
export const FIND_LAPTOP_BY_ID_SUCCESS = 'FIND_LAPTOP_BY_ID_SUCCESS';
export const FIND_LAPTOP_BY_ID_FAILURE = 'FIND_LAPTOP_BY_ID_FAILURE';

export const FIND_LAPTOPS_BY_FILTER_REQUEST = 'FIND_LAPTOPS_BY_FILTER_REQUEST';
export const FIND_LAPTOPS_BY_FILTER_SUCCESS = 'FIND_LAPTOPS_BY_FILTER_SUCCESS';
export const FIND_LAPTOPS_BY_FILTER_FAILURE = 'FIND_LAPTOPS_BY_FILTER_FAILURE';

export const SEARCH_LAPTOP_REQUEST = "SEARCH_LAPTOP_REQUEST";
export const SEARCH_LAPTOP_SUCCESS = "SEARCH_LAPTOP_SUCCESS";
export const SEARCH_LAPTOP_FAILURE = "SEARCH_LAPTOP_FAILURE";
